name: Build Windows EXE
on: [push]
jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      
      - uses: subosito/flutter-action@v2
        with:
          channel: stable
          flutter-version: '3.29.3'
          
      # Klasör kontrolü ekleyin
      - name: Check project structure
        run: |
          ls -la
          if [ -f "pubspec.yaml" ]; then
            echo "Flutter project found in root"
          else
            echo "ERROR: Not a valid Flutter project!"
            exit 1
          fi
          
      - run: flutter pub get
      - run: flutter build windows
      
      - uses: actions/upload-artifact@v4
        with:
          name: rustdesk.exe
          path: build/windows/runner/Release/rustdesk.exe