name: Build Windows EXE
on: [push]
jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      
      - uses: subosito/flutter-action@v2
        with:
          channel: stable
          flutter-version: '3.29.3'
          
      # Flutter proje dizinine geç
      - name: Navigate to Flutter project
        shell: pwsh
        run: |
          cd flutter
          if (!(Test-Path "pubspec.yaml")) {
            Write-Host "ERROR: pubspec.yaml not found in flutter directory!"
            exit 1
          }
          
      # Tüm komutları flutter dizininde çalıştır
      - name: Install dependencies
        run: flutter pub get
        working-directory: ./flutter
      
      - name: Build Windows
        run: flutter build windows
        working-directory: ./flutter
      
      - uses: actions/upload-artifact@v4
        with:
          name: rustdesk.exe
          path: flutter/build/windows/runner/Release/rustdesk.exe