name: Build Windows EXE
on: [push]
jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      
      # Flutter'i kur
      - uses: subosito/flutter-action@v2
        with:
          channel: stable
          flutter-version: '3.29.3'
          
      # Proje dizinine git (Linux stili yol kullanın)
      - name: Navigate to project
        run: cd ./rustdesk
        shell: bash
        
      # Bağımlılıkları yükle
      - name: Install dependencies
        run: flutter pub get
        
      # Build işlemi
      - name: Build Windows
        run: flutter build windows
        
      # Çıktıyı kaydet
      - uses: actions/upload-artifact@v4
        with:
          name: rustdesk.exe
          path: ./rustdesk/build/windows/runner/Release/rustdesk.exe